import { readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import Papa from 'papaparse';
import { z } from 'zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const CATEGORY_IDS = [
  'ethics',
  'philosophy',
  'politics',
  'technology',
  'law',
  'social',
  'economy',
  'life',
  'identity',
  'relationship',
  'education',
  'career',
  'environment',
  'religion',
  'psychology',
  'science',
  'power',
  'future',
  'paradox',
  'local',
  'popculture',
] as const;

const QuestionRowSchema = z.object({
  qid: z.string().min(1),
  category_id: z.enum(CATEGORY_IDS),
  level: z.enum(['easy', 'medium', 'hard']),
  q_en: z.string().min(1),
  hint_en: z.string().optional().default(''),
  persp_en: z.string().min(1),
  q_id: z.string().min(1),
  hint_id: z.string().optional().default(''),
  persp_id: z.string().min(1),
});

type QuestionRow = z.infer<typeof QuestionRowSchema>;

const csvPath = resolve(ROOT, 'src/data/questions.csv');
const outPath = resolve(ROOT, 'src/data/questions.generated.ts');

const raw = readFileSync(csvPath, 'utf-8');
const { data, errors } = Papa.parse<Record<string, string>>(raw, {
  header: true,
  skipEmptyLines: true,
});

if (errors.length > 0) {
  console.error('CSV parse errors:', errors);
  process.exit(1);
}

const questions: QuestionRow[] = [];
const qids = new Set<string>();

for (let i = 0; i < data.length; i += 1) {
  const row = data[i];
  const result = QuestionRowSchema.safeParse(row);

  if (!result.success) {
    console.error(`Row ${i + 2}: validation failed:`);
    console.error(result.error.issues);
    process.exit(1);
  }

  const question = result.data;

  if (qids.has(question.qid)) {
    console.error(`Duplicate qid: "${question.qid}" at row ${i + 2}`);
    process.exit(1);
  }

  qids.add(question.qid);
  questions.push(question);
}

const output = `// AUTOGENERATED — do not edit. Source: src/data/questions.csv\n// Generated: ${new Date().toISOString()}\n// Run \`bun run prebuild\` to regenerate.\n\nimport type { Question } from '../types/question';\n\nexport const QUESTIONS: readonly Question[] = ${JSON.stringify(questions, null, 2)} as const;\n\nexport const QUESTION_COUNT = ${questions.length};\n`;

writeFileSync(outPath, output, 'utf-8');
process.stdout.write(`Generated ${questions.length} questions → ${outPath}\n`);
